export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START"
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS"
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL"


export const FACEBOOK_SIGN_IN_START = "FACEBOOK_SIGN_IN_START"
export const FACEBOOK_SIGN_IN_SUCCESS = "FACEBOOK_SIGN_IN_SUCCESS"
export const FACEBOOK_SIGN_IN_FAIL = "FACEBOOK_SIGN_IN_FAIL"


export const GET_HOME_PAGE_START = "GET_HOME_PAGE_START";
export const GET_HOME_PAGE_SUCCESS = "GET_HOME_PAGE_SUCCESS";
export const GET_HOME_PAGE_ERROR = "GET_HOME_PAGE_ERROR";



export const GET_SeeMore_PAGE_START = "GET_SeeMore_PAGE_START";
export const GET_SeeMore_PAGE_SUCCESS = "GET_SeeMore_PAGE_SUCCESS";
export const GET_SeeMore_PAGE_ERROR = "GET_SeeMore_PAGE_ERROR";